from .ap_text_mask import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .ap_mask_trim import (
    NODE_CLASS_MAPPINGS as _TRIM_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _TRIM_DISPLAY,
)

NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **_TRIM_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **_TRIM_DISPLAY}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
